In [2]:
import numpy as np
from sklearn import preprocessing
from tensorflow.keras.datasets import mnist


In [9]:

# Define the One-hot Encoder
ohe = preprocessing.OneHotEncoder()

# Load MNIST data
(X_train, y_train), (X_test, y_test) = mnist.load_data()

# Reshape data
y_train = y_train.reshape(-1, 1)
y_test = y_test.reshape(-1, 1)


# Fit and transform training data
ohe.fit(y_train)
transformed_train = ohe.transform(y_train).toarray()

# Fit and transform testing data
ohe.fit(y_test)
transformed_test = ohe.transform(y_test).toarray()

# Print results
print(f'Value without encoding: {y_test[123]}')
print(f'Value with encoding: {transformed_test[123]}')


Value without encoding: [6]
Value with encoding: [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]


In [10]:
X_train = X_train.reshape(X_train.shape[0], X_train.shape[1]*X_train.shape[2])
X_test = X_test.reshape(X_test.shape[0], X_test.shape[1]*X_test.shape[2])
print(X_train.shape)
print(X_test.shape)
print(transformed_train.shape)
print(transformed_test.shape)

(60000, 784)
(10000, 784)
(60000, 10)
(10000, 10)


In [12]:
with open('mnist_X_train', 'wb') as f:
    np.save(f, X_train)
with open('mnist_X_test', 'wb') as f:
    np.save(f, X_test)
with open('mnist_y_train', 'wb') as f:
    np.save(f, y_train)
with open('mnist_y_test', 'wb') as f:
    np.save(f, y_test)
with open('mnist_y_train_ohe', 'wb') as f:
    np.save(f, transformed_train)
with open('mnist_y_test_ohe', 'wb') as f:
    np.save(f, transformed_test)

In [13]:
print(transformed_train)


[[0. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 1. 0.]]
